server:
  port: 8080
spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/iot}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false